language: java
dist: precise
before_script: cd api/
script: mvn test -Ptest -DmessageBirdAccessKey=test_iQpAp0KCs5GCsMpDhIx2leuNB -DmessageBirdMSISDN=31612345678
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
