language: java
dist: precise
before_script: cd api/
script: if [[ "$TRAVIS_JDK_VERSION" == "openjdk6" ]]; then mvn test -Ptest -Dhttps.protocols=TLSv1 -DmessageBirdAccessKey=test_iQpAp0KCs5GCsMpDhIx2leuNB -DmessageBirdMSISDN=31612345678; else mvn test -Ptest -Dhttps.protocols=TLSv1.2 -DmessageBirdAccessKey=test_iQpAp0KCs5GCsMpDhIx2leuNB -DmessageBirdMSISDN=31612345678; fi
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
matrix:
  allow_failures:
    - openjdk6