language: java
dist: trusty
before_script: cd api/
script: mvn test -Ptest -DmessageBirdAccessKey=test_iQpAp0KCs5GCsMpDhIx2leuNB -DmessageBirdMSISDN=31612345678
addons:
  apt:
    packages:
      - openjdk-6-jdk
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk6
  - openjdk7
  - openjdk8

matrix:
  allow_failures:
    - jdk: openjdk6
